# there's default options, except logstash.host (default: localhost)
logging-api:
  file:
    path: logs/myLogs.log
    log-pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    log-level: INFO
  console:
    log-pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    log-level: INFO
  elastic:
    log-level: INFO
  logstash:
    host: 192.168.56.101
    port: 5300
