#logging:
#  pattern:
#    console: "====%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level  %class{36}.%M %L  - %msg%n"
#  file:
#    name: logs/LogELK.log
#    path: logs/LogELK.log

fpath: logs/fpath.log

logger-elk:
  server: localhost
  port: 8080
  file-path: logs/for-elk.log

server:
  port: 8184
