#logging.level.org.springframework: DEBUG

#logging:
#  pattern:
#    console: "====%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level  %class{36}.%M %L  - %msg%n"
#  file:
#    name: logs/LogELK.log
#    path: logs/LogELK.log



server:
  port: 8184

#logging-elk:
#  file-path: logs/for-elk.log
#  server: localhost
#  port: 8080


#logging.level
